### PR TITLE
New verification system.

### PR DESCRIPTION
**Pull request by Icesory**
In the simulation it works fine.

### CODE REVIEW

**Comment by sweetpi** [comment]
@Icesory What is exactly the problem with the generic verify function?

**Comment by Icesory** [comment]
What do you think to verify the packages in pimatic? So we can create easier verify functions.

**Comment by sweetpi** [comment]
> What do you think to verify the packages in pimatic? So we can create easier verify functions.

Yes I wanted to do this too. I would have no problem to skip the verification at all, if we find a way to detect start and end of a package without verify.

**Comment by Icesory** [comment]
With a nice algorithm we can detect the a running transmission and save this as a package. The algorithm can make a failure correction and improves the signal quality. I have some ideas for this but in 2 weeks starts my studies examinations.

**Comment by sweetpi** [comment]
> I have some ideas for this but in 2 weeks starts my studies examinations.

No worries, looking forward to hear it. I'm most productive at this times :D. Try to keep focused on your exams ;)

**Pull request merged**
